package:
  name: gpu_tpu_lab_server
  version: 0.0.1
source:
  sha256: 1a558dffd7944ea22e0e728878abd92916415059919374ad14280048702caaf6
  url: https://files.pythonhosted.org/packages/1c/ff/01f1ca2f718d24c7c0d8696d8af2672518bad0ec0fcaf03b0efa141dd836/gpu_tpu_lab_server-0.0.1.tar.gz
about:
  dev_url: https://fastdaima.github.io
  doc_url: https://fastdaima.github.io
  home: https://fastdaima.github.io
  license: Apache Software
  license_family: APACHE
  summary: Running a jupyter lab or vs code server environment from colab with google
    drive support
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - fastdaima
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - gpu_tpu_lab_server
